INSERT INTO Obra (idLivro, nome_obra, area_id, data_publicacao, autor, tags, genero, created_at, tipo_obra) VALUES
(2, '1984', 3, '1949-06-08', 'George Orwell', 'distopia,futurismo,política', 'Ficção Científica', NOW(), 'Livro'),
(3, 'O Senhor dos Anéis: A Sociedade do Anel', 4, '1954-07-29', 'J.R.R. Tolkien', 'fantasia,aventura', 'Fantasia', NOW(), 'Livro'),
(4, 'Harry Potter e a Pedra Filosofal', 4, '1997-06-26', 'J.K. Rowling', 'magia,escola,aventura', 'Fantasia', NOW(), 'Livro'),
(5, 'Cem Anos de Solidão', 6, '1997-06-26', 'Gabriel García Márquez', 'realismo mágico,família', 'Literatura Latino-Americana', NOW(), 'Livro'),
(6, 'A Arte da Guerra', 2, '1997-06-26', 'Sun Tzu', 'estratégia,guerra', 'Filosofia', NOW(), 'Livro'),
(7, 'O Pequeno Príncipe', 1, '1943-04-06', 'Antoine de Saint-Exupéry', 'infantil,filosofia', 'Literatura Infantil', NOW(), 'Livro'),
(8, 'Crime e Castigo', 6, '1866-01-01', 'Fiódor Dostoiévski', 'psicológico,crime', 'Romance', NOW(), 'Livro'),
(9, 'National Geographic - Edição 250', 9, '2020-10-01', 'Vários Autores', 'natureza,ciência,fotografia', 'Revista', NOW(), 'Revista'),
(10, 'A Metamorfose', 6, '1915-10-01', 'Franz Kafka', 'existencialismo,absurdo', 'Literatura Estrangeira', NOW(), 'Livro'),
(11, 'O Hobbit', 4, '1937-09-21', 'J.R.R. Tolkien', 'fantasia,aventura', 'Fantasia', NOW(), 'Livro'),
(12, 'O Guia do Mochileiro das Galáxias', 3, '1979-10-12', 'Douglas Adams', 'ficção científica,humor', 'Ficção Científica', NOW(), 'Livro'),
(13, 'Maus', 10, '1986-01-01', 'Art Spiegelman', 'histórico,guerra,holocausto', 'Graphic Novel', NOW(), 'Quadrinho'),
(14, 'A Revolução dos Bichos', 3, '1945-08-17', 'George Orwell', 'alegoria,política', 'Ficção', NOW(), 'Livro'),
(15, 'O Nome da Rosa', 6, '1980-10-01', 'Umberto Eco', 'mistério,histórico', 'Romance', NOW(), 'Livro'),
(16, 'O Alquimista', 2, '1988-01-01', 'Paulo Coelho', 'aventura,filosofia', 'Ficção', NOW(), 'Livro'),
(17, 'A Divina Comédia', 8, '1320-01-01', 'Dante Alighieri', 'poesia,religião', 'Poesia', NOW(), 'Livro'),
(18, 'Scientific American - Edição 325', 9, '2021-03-15', 'Vários Autores', 'tecnologia,ciência', 'Revista', NOW(), 'Revista'),
(19, 'O Retrato de Dorian Gray', 6, '1890-07-01', 'Oscar Wilde', 'filosofia,vaidade', 'Romance', NOW(), 'Livro'),
(20, 'Ensaio sobre a Cegueira', 6, '1995-01-01', 'José Saramago', 'alegoria,existencialismo', 'Ficção', NOW(), 'Livro'),
(21, 'O Mundo de Sofia', 2, '1991-12-05', 'Jostein Gaarder', 'filosofia,história', 'Romance', NOW(), 'Livro'),
(22, 'A Culpa é das Estrelas', 6, '2012-01-10', 'John Green', 'romance,doença', 'Romance', NOW(), 'Livro'),
(23, 'O Silmarillion', 4, '1977-09-15', 'J.R.R. Tolkien', 'fantasia,mitologia', 'Fantasia', NOW(), 'Livro'),
(24, 'O Estrangeiro', 2, '1942-01-01', 'Albert Camus', 'existencialismo,filosofia', 'Romance', NOW(), 'Livro'),
(25, 'A Menina que Roubava Livros', 6, '2005-03-14', 'Markus Zusak', 'guerra,histórico', 'Romance', NOW(), 'Livro');
