-- Inserindo obras de exemplo na tabela Obra com now() em minúsculo
INSERT INTO Obra (idLivro, nome_obra, data_publicacao, autor, tags, genero, created_at, tipo_obra) VALUES
(2, '1984', '1949-06-08', 'George Orwell', 'distopia,futurismo,política', 'Ficção Científica', now(), 'Livro'),
(3, 'O Senhor dos Anéis: A Sociedade do Anel', '1954-07-29', 'J.R.R. Tolkien', 'fantasia,aventura', 'Fantasia', now(), 'Livro'),
(4, 'Harry Potter e a Pedra Filosofal', '1997-06-26', 'J.K. Rowling', 'magia,escola,aventura', 'Fantasia', now(), 'Livro'),
(5, 'Cem Anos de Solidão', '1997-06-26', 'Gabriel García Márquez', 'realismo mágico,família', 'Literatura Latino-Americana', now(), 'Livro'),
(6, 'A Arte da Guerra', '1997-06-26', 'Sun Tzu', 'estratégia,guerra', 'Filosofia', now(), 'Livro'),
(7, 'O Pequeno Príncipe', '1943-04-06', 'Antoine de Saint-Exupéry', 'infantil,filosofia', 'Literatura Infantil', now(), 'Livro'),
(8, 'Crime e Castigo', '1866-01-01', 'Fiódor Dostoiévski', 'psicológico,crime', 'Romance', now(), 'Livro'),
(9, 'National Geographic - Edição 250', '2020-10-01', 'Vários Autores', 'natureza,ciência,fotografia', 'Revista', now(), 'Revista'),
(10, 'A Metamorfose', '1915-10-01', 'Franz Kafka', 'existencialismo,absurdo', 'Literatura Estrangeira', now(), 'Livro'),
(11, 'O Hobbit', '1937-09-21', 'J.R.R. Tolkien', 'fantasia,aventura', 'Fantasia', now(), 'Livro'),
(12, 'O Guia do Mochileiro das Galáxias', '1979-10-12', 'Douglas Adams', 'ficção científica,humor', 'Ficção Científica', now(), 'Livro'),
(13, 'Maus', '1986-01-01', 'Art Spiegelman', 'histórico,guerra,holocausto', 'Graphic Novel', now(), 'Quadrinho'),
(14, 'A Revolução dos Bichos', '1945-08-17', 'George Orwell', 'alegoria,política', 'Ficção', now(), 'Livro'),
(15, 'O Nome da Rosa', '1980-10-01', 'Umberto Eco', 'mistério,histórico', 'Romance', now(), 'Livro'),
(16, 'O Alquimista', '1988-01-01', 'Paulo Coelho', 'aventura,filosofia', 'Ficção', now(), 'Livro'),
(17, 'A Divina Comédia', '1320-01-01', 'Dante Alighieri', 'poesia,religião', 'Poesia', now(), 'Livro'),
(18, 'Scientific American - Edição 325', '2021-03-15', 'Vários Autores', 'tecnologia,ciência', 'Revista', now(), 'Revista'),
(19, 'O Retrato de Dorian Gray', '1890-07-01', 'Oscar Wilde', 'filosofia,vaidade', 'Romance', now(), 'Livro'),
(20, 'Ensaio sobre a Cegueira', '1995-01-01', 'José Saramago', 'alegoria,existencialismo', 'Ficção', now(), 'Livro'),
(21, 'O Mundo de Sofia', '1991-12-05', 'Jostein Gaarder', 'filosofia,história', 'Romance', now(), 'Livro'),
(22, 'A Culpa é das Estrelas', '2012-01-10', 'John Green', 'romance,doença', 'Romance', now(), 'Livro'),
(23, 'O Silmarillion', '1977-09-15', 'J.R.R. Tolkien', 'fantasia,mitologia', 'Fantasia', now(), 'Livro'),
(24, 'O Estrangeiro', '1942-01-01', 'Albert Camus', 'existencialismo,filosofia', 'Romance', now(), 'Livro'),
(25, 'A Menina que Roubava Livros', '2005-03-14', 'Markus Zusak', 'guerra,histórico', 'Romance', now(), 'Livro');